#!/usr/bin/env python3
"""One-shot migration helper: pull the glossary and mission tables out of the
hand-written pages and into single canonical data files.

Each page currently carries its own copy of the terms it references. Where the
copies disagree, the most widely used wording wins and the alternatives are
written to a report so a human can settle them.
"""

from __future__ import annotations

import collections
import html
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
DATA = ROOT / "data"

DEFS_BLOCK = re.compile(r"var DEFS = \{(.*?)\n  \};", re.S)
DEFS_ENTRY = re.compile(
    r"'((?:[^'\\]|\\.)*)':\s*\['((?:[^'\\]|\\.)*)',\s*'((?:[^'\\]|\\.)*)'\]"
)
MISSION_BLOCK = re.compile(r"var M = \{(.*?)\n  \};", re.S)
GLOSSARY_ENTRY = re.compile(
    r'<article class="term" data-term="([^"]*)" data-body="([^"]*)"[^>]*>\s*<h2>(.*?)</h2>',
    re.S,
)


def js_unescape(text: str) -> str:
    text = re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: chr(int(m.group(1), 16)), text)
    return text.replace("\\'", "'").replace('\\"', '"').replace("\\\\", "\\")


def yaml_scalar(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def collect_definitions() -> tuple[dict, dict]:
    """term -> body -> [pages], and term -> {titles}."""
    bodies: dict[str, dict[str, list[str]]] = collections.defaultdict(
        lambda: collections.defaultdict(list)
    )
    titles: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)

    for page in sorted(DOCS.rglob("*.html")):
        block = DEFS_BLOCK.search(page.read_text(errors="replace"))
        if not block:
            continue
        rel = page.relative_to(DOCS).as_posix()
        for match in DEFS_ENTRY.finditer(block.group(1)):
            key, title, body = (js_unescape(g) for g in match.groups())
            bodies[key][body.strip()].append(rel)
            titles[key][title.strip()] += 1
    return bodies, titles


def canonical_glossary() -> dict[str, dict[str, str]]:
    text = (DOCS / "glossary.html").read_text()
    return {
        m.group(1): {
            "title": html.unescape(m.group(3)).strip(),
            "body": html.unescape(m.group(2)).strip(),
        }
        for m in GLOSSARY_ENTRY.finditer(text)
    }


def is_python_only(pages: list[str]) -> bool:
    return all(p.startswith("Python_Labs/") for p in pages)


def build_glossary(bodies, titles, canon):
    """Majority wording wins; a clean C-vs-Python split becomes a variant."""
    terms: dict[str, dict] = {}
    conflicts: dict[str, list] = {}

    for key in sorted(bodies):
        variants = sorted(bodies[key].items(), key=lambda kv: -len(kv[1]))
        title = titles[key].most_common(1)[0][0]

        python_variant = None
        if len(variants) > 1:
            python_only = [v for v in variants if is_python_only(v[1])]
            shared = [v for v in variants if not is_python_only(v[1])]
            if len(python_only) == 1 and len(shared) == 1:
                python_variant = python_only[0][0]
                variants = shared

        entry = {"title": title, "body": variants[0][0]}
        if python_variant:
            entry["python"] = python_variant
        if key not in canon:
            entry["source"] = "rules"
        terms[key] = entry

        remaining = variants[1:]
        if remaining:
            conflicts[key] = [
                {"body": body, "pages": pages} for body, pages in remaining
            ]
    return terms, conflicts


def build_missions() -> dict[int, dict]:
    missions: dict[int, dict] = {}
    for page in sorted(DOCS.rglob("*.html")):
        block = MISSION_BLOCK.search(page.read_text(errors="replace"))
        if not block:
            continue
        for match in re.finditer(r"(\d+):\s*(\{.*?\})", block.group(1), re.S):
            missions.setdefault(int(match.group(1)), json.loads(match.group(2)))
    return dict(sorted(missions.items()))


def write_glossary(terms: dict[str, dict]) -> None:
    lines = [
        "# Generated by tools/extract_data.py from the per-page DEFS blocks.",
        "# Single source of truth for every definition popup and for the glossary page.",
        "",
    ]
    for key, entry in terms.items():
        lines.append(f"{yaml_scalar(key)}:")
        lines.append(f"  title: {yaml_scalar(entry['title'])}")
        lines.append(f"  body: {yaml_scalar(entry['body'])}")
        if "python" in entry:
            lines.append(f"  python: {yaml_scalar(entry['python'])}")
        if "source" in entry:
            lines.append(f"  source: {yaml_scalar(entry['source'])}")
    (DATA / "glossary.yaml").write_text("\n".join(lines) + "\n")


def write_missions(missions: dict[int, dict]) -> None:
    lines = [
        "# Generated by tools/extract_data.py from the per-page mission tables.",
        "",
    ]
    for number, mission in missions.items():
        lines.append(f'"{number}":')
        lines.append(f"  title: {yaml_scalar(mission['title'])}")
        lines.append("  tiers:")
        for tier in mission["tiers"]:
            lines.append(f"    - {yaml_scalar(tier)}")
    (DATA / "missions.yaml").write_text("\n".join(lines) + "\n")


def write_conflicts(conflicts: dict) -> None:
    lines = [
        "# Terms that are defined more than one way across the site.",
        "# The wording in glossary.yaml is whichever appears on the most pages;",
        "# everything below was displaced and needs a human decision.",
        "",
    ]
    for key, variants in sorted(conflicts.items()):
        lines.append(f"{yaml_scalar(key)}:")
        for variant in variants:
            lines.append(f"  - body: {yaml_scalar(variant['body'])}")
            lines.append("    pages:")
            for page in variant["pages"]:
                lines.append(f"      - {yaml_scalar(page)}")
    (DATA / "glossary-conflicts.yaml").write_text("\n".join(lines) + "\n")


def main() -> None:
    DATA.mkdir(exist_ok=True)
    bodies, titles = collect_definitions()
    canon = canonical_glossary()
    terms, conflicts = build_glossary(bodies, titles, canon)
    missions = build_missions()

    write_glossary(terms)
    write_missions(missions)
    write_conflicts(conflicts)

    copies = sum(len(pages) for term in bodies.values() for pages in term.values())
    print(f"glossary.yaml           {len(terms):>4} terms (replacing {copies} pasted copies)")
    print(f"missions.yaml           {len(missions):>4} missions")
    print(f"glossary-conflicts.yaml {len(conflicts):>4} terms needing a human decision")


if __name__ == "__main__":
    main()
